### ISSUE TITLE
mpv in several versions

### ISSUE THREAD

**Issue by RalfWerner** [Neo-Oli/Termux-Mpv#12]
Hi @Neo-Oli 
In the past I've used the `mpv-x` package of x11 packages from @xeffyr to display small videos (successfully with audio+video output) with termux. This has not been working properly for some time. In the meantime there was only _audio output_ and I set up a proot/ubuntu and installed the media player there too with _video output_ only. Try again now: This doubles ubuntu from 738Mb to 1.5Gb.
After the last termux `pkg up/apt-get` I get the following messages in various ARCH from termux (`[~]$`)and ubuntu (`uu[~]#`):
```
[~]$ export DISPLAY=:0;mpv -vo x11 i/check.mp4
CANNOT LINK EXECUTABLE "mpv": cannot locate symbol "XzUnpacker_Construct" referenced by "/system/lib/libunwind.so"...
CANNOT LINK EXECUTABLE "mpv": cannot locate symbol "u_charDirection_58" referenced by "/system/lib64/libandroid_runtime.so"...
Aborted
...

uu[~]# apt-get install mpv
Reading package lists... Done
Building dependency tree Reading state information... Done
mpv is already the newest version (0.29.1-1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
3 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n]
Setting up libfprint0:armhf (1:0.8.2-3) ...
Failed to scan devices: No such file or directory
dpkg: error processing package libfprint0:armhf (--configure): installed libfprint0:armhf package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of fprintd: fprintd depends on libfprint0 (>= 1:0.4.0); however:
  Package libfprint0:armhf is not configured yet.
dpkg: error processing package fprintd (--configure): dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libpam-fprintd:armhf: libpam-fprintd:armhf depends on fprintd (= 0.8.1-1); however:
  Package fprintd is not configured yet.

dpkg: error processing package libpam-fprintd:armhf (--configure): dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.29-0ubuntu2) ...
No apport report written because the error message indicates its a followup error from a previous failure. Errors were encountered while processing:
 libfprint0:armhf
 fprintd
 libpam-fprintd:armhf
E: Sub-process /usr/bin/dpkg returned an error code (1)
uu[~]#
uu[~]# ll u/bin/mpv
-rwxr-xr-x. 1 root root 1354328 Nov  9  2018 u/bin/mpv
uu[~]# export DISPLAY=:0;mpv -vo x11 i/check.mp4
mpv: error while loading shared libraries: libx264.so.155: cannot enable executable stack as shared object requires: Permission denied
```
I discovered today your `Termux-mpv` and have a few questions about it:
- is it with `Termux-mpv` audio+video output possible as with `mpv-x` and did you compare the different media player installations?
- if yes how much storage is used for `Termux-mpv` and can you say something about the messages (bugs/errors) above?

**Comment by Neo-Oli** [comment]
@RalfWerner I think you misunderstand what termux-mpv is. Termux-mpv is just a wrapper around whatever version of mpv you have installed. All it does is add a notification about running mpv instances with a play, prev and next button.
https://raw.githubusercontent.com/Neo-Oli/Termux-Mpv/master/Screenshots/Notification-Media-Controls-small.png
It isn't another version of mpv. About the errors you better ask in termux-packages or x11-packages.

**Comment by RalfWerner** [comment]
> I think you misunderstand what termux-mpv is

I thought so and I wanted to know if you made comparisons (apparently not). My experience with API is ambivalent because the parallel processes often collide with termux

Will try to install **mpv App** and make experiance with `termux-mvp` - thanks so far
