### ISSUE TITLE
Quit mpv when notification dismissed

### ISSUE THREAD

**Issue by qoxxxx** [Neo-Oli/Termux-Mpv#6]
Dismissing the notification doesn't seem to do anything for me.

**Comment by Neo-Oli** [comment]
Unfortunately this is not possible with the current implementation of the API. You will need to create a new issue at https://github.com/termux/termux-api/issues to allow an action to be registered for the dismissal of notifications. Once that is available I will gladly and swiftly implement this feature.

**Comment by Neo-Oli** [comment]
If you update termux-mpv, the termux:Api app and the termux-api package, this should now work.
