### ISSUE TITLE
How to use it 

### ISSUE THREAD

**Issue by Draconixss** [Neo-Oli/Termux-Mpv#8]
I didnt know how to use it
Sorry im a newbie :(

**Comment by 5c0tt-b0t** [comment]
Exactly the same as `mpv`, but you write `termuxmpv` instead.

**Example:**
`termuxmpv SONG`
(**replace** SONG with the name of **your** song or album **file name**)
e.g `termuxmpv 2pac-Changes.mp3`
(this command plays the song **if** its in your current directory)
**if** your not in the songs directory then state it like so:
`termuxmpv /sdcard/Music/2pac-Changes.mp3` etc (obviously, replace this with your own path)
Need to play more than one song?
`termuxmpv DIRECTORY`
(plays a whole directory, as a playlist **if** you have more than one song in the folder)
Thats all you need to know!
Need more help? to see all commands:
`termuxmpv --help`

**Comment by godwinwaswa** [comment]
Not working either

**Comment by seisdr** [comment]
mpv complied without video option it won't display on xserver emulator
